# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 298706b1a215db6de4a0f4363a8c008f0327bc301cad6a62ae3346ddbf46ff2c8f790aa3e90dca37a9d7d4496bcd73d2704e5b1dbb3ec4f1dd04f8d4bc8a5f6f

test:
  secret_key_base: 93bc7eae189fca347e3a8896bf6afb4cedc323e59de4007ba0a97b86fe3a881510bb236e9be21d90f8d55306c0e600d939651f2a1d7df8847276f47325e2b0bc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
